version: '3.9'

services:
  api:
    image: image-editor-back
    container_name: fastapi-container
    build:
      context: ./image-editor-back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
      
  frontend:
    image: image-editor-front
    container_name: irex-portal
    build: 
      context: ./image-editor-front
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:3000"
    networks:
      - app-network
    depends_on:
      - image-editor-back

networks:
  app-network:
    driver: bridge
