version: '3.9'

services:
  api:
    image: image-editor-back
    container_name: fastapi-container
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: image-editor-front
    container_name: irex-portal
    build: 
      context: ./front
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - app-network
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
